/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_ajout (void)
{
  GtkWidget *window_ajout;
  GtkWidget *fixed1;
  GtkWidget *entry_id;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *entry2;
  GtkWidget *entry4;
  GtkWidget *eventbox5;
  GtkWidget *label5;
  GtkWidget *eventbox6;
  GtkWidget *label;
  GtkWidget *eventbox7;
  GtkWidget *label7;
  GtkWidget *eventbox8;
  GtkWidget *label8;
  GtkWidget *eventbox9;
  GtkWidget *label10;
  GtkWidget *eventbox10;
  GtkWidget *label9;
  GtkWidget *eventbox11;
  GtkWidget *label11;
  GtkWidget *eventbox12;
  GtkWidget *label12;
  GtkWidget *eventbox13;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *eventbox14;
  GtkWidget *radiobutton2;
  GtkWidget *eventbox15;
  GtkWidget *checkbutton1;
  GtkWidget *eventbox16;
  GtkWidget *checkbutton2;
  GtkWidget *eventbox17;
  GtkWidget *checkbutton3;
  GtkWidget *eventbox18;
  GtkWidget *button_confirmer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *eventbox19;
  GtkWidget *label13;
  GtkWidget *entry3;
  GtkWidget *eventbox20;
  GtkWidget *comboboxentry1;
  GtkWidget *eventbox67;
  GtkWidget *buttonretourajout;
  GtkWidget *image23;
  GtkWidget *image13;

  window_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajout), _("Ajouter un menu"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_ajout), fixed1);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id, 150, 60);
  gtk_widget_set_size_request (entry_id, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 150, 110);
  gtk_widget_set_size_request (spinbutton1, 60, 30);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2, 220, 110);
  gtk_widget_set_size_request (spinbutton2, 60, 30);

  spinbutton3_adj = gtk_adjustment_new (2021, 2021, 2070, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton3, 290, 110);
  gtk_widget_set_size_request (spinbutton3, 70, 30);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 240, 230);
  gtk_widget_set_size_request (entry2, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed1), entry4, 240, 310);
  gtk_widget_set_size_request (entry4, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox5, 0, 60);
  gtk_widget_set_size_request (eventbox5, 150, 30);

  label5 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label5);
  gtk_container_add (GTK_CONTAINER (eventbox5), label5);
  gtk_widget_set_size_request (label5, 150, 30);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 0, 110);
  gtk_widget_set_size_request (eventbox6, 150, 30);

  label = gtk_label_new (_("Date"));
  gtk_widget_show (label);
  gtk_container_add (GTK_CONTAINER (eventbox6), label);
  gtk_widget_set_size_request (label, 150, 30);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox7, 0, 160);
  gtk_widget_set_size_request (eventbox7, 150, 30);

  label7 = gtk_label_new (_("Type"));
  gtk_widget_show (label7);
  gtk_container_add (GTK_CONTAINER (eventbox7), label7);
  gtk_widget_set_size_request (label7, 150, 30);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox8, 0, 200);
  gtk_widget_set_size_request (eventbox8, 150, 30);

  label8 = gtk_label_new (_("Menu"));
  gtk_widget_show (label8);
  gtk_container_add (GTK_CONTAINER (eventbox8), label8);
  gtk_widget_set_size_request (label8, 150, 30);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox9, 80, 270);
  gtk_widget_set_size_request (eventbox9, 150, 30);

  label10 = gtk_label_new (_("Plat principal"));
  gtk_widget_show (label10);
  gtk_container_add (GTK_CONTAINER (eventbox9), label10);
  gtk_widget_set_size_request (label10, 150, 30);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 80, 230);
  gtk_widget_set_size_request (eventbox10, 150, 30);

  label9 = gtk_label_new (_("Entree"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (eventbox10), label9);
  gtk_widget_set_size_request (label9, 150, 30);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox11, 80, 310);
  gtk_widget_set_size_request (eventbox11, 150, 30);

  label11 = gtk_label_new (_("Dessert"));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (eventbox11), label11);
  gtk_widget_set_size_request (label11, 150, 30);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox12, 0, 350);
  gtk_widget_set_size_request (eventbox12, 150, 30);

  label12 = gtk_label_new (_("Regime"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox12), label12);
  gtk_widget_set_size_request (label12, 150, 30);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox13, 150, 350);
  gtk_widget_set_size_request (eventbox13, 150, 30);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Vegetarien"));
  gtk_widget_show (radiobutton1);
  gtk_container_add (GTK_CONTAINER (eventbox13), radiobutton1);
  gtk_widget_set_size_request (radiobutton1, 150, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox14, 300, 350);
  gtk_widget_set_size_request (eventbox14, 150, 30);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Standard"));
  gtk_widget_show (radiobutton2);
  gtk_container_add (GTK_CONTAINER (eventbox14), radiobutton2);
  gtk_widget_set_size_request (radiobutton2, 150, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox15, 40, 410);
  gtk_widget_set_size_request (eventbox15, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Etudiants"));
  gtk_widget_show (checkbutton1);
  gtk_container_add (GTK_CONTAINER (eventbox15), checkbutton1);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox16, 160, 410);
  gtk_widget_set_size_request (eventbox16, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Professeurs"));
  gtk_widget_show (checkbutton2);
  gtk_container_add (GTK_CONTAINER (eventbox16), checkbutton2);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox17, 288, 410);
  gtk_widget_set_size_request (eventbox17, 118, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Techniciens"));
  gtk_widget_show (checkbutton3);
  gtk_container_add (GTK_CONTAINER (eventbox17), checkbutton3);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox18, 8, 456);
  gtk_widget_set_size_request (eventbox18, 150, 30);

  button_confirmer = gtk_button_new ();
  gtk_widget_show (button_confirmer);
  gtk_container_add (GTK_CONTAINER (eventbox18), button_confirmer);
  gtk_widget_set_size_request (button_confirmer, 150, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_confirmer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Confirmer </span></b>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox5), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox19, 208, 448);
  gtk_widget_set_size_request (eventbox19, 192, 40);

  label13 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\">       \n\n\n\n</span></b>"));
  gtk_widget_show (label13);
  gtk_container_add (GTK_CONTAINER (eventbox19), label13);
  gtk_widget_set_size_request (label13, 192, 40);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 240, 272);
  gtk_widget_set_size_request (entry3, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox20, 170, 160);
  gtk_widget_set_size_request (eventbox20, 200, 30);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_container_add (GTK_CONTAINER (eventbox20), comboboxentry1);
  gtk_widget_set_size_request (comboboxentry1, 200, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Petit_dejeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Dejeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Dinner"));

  eventbox67 = gtk_event_box_new ();
  gtk_widget_show (eventbox67);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox67, 16, 16);
  gtk_widget_set_size_request (eventbox67, 66, 29);

  buttonretourajout = gtk_button_new ();
  gtk_widget_show (buttonretourajout);
  gtk_container_add (GTK_CONTAINER (eventbox67), buttonretourajout);
  gtk_widget_set_size_request (buttonretourajout, 66, 29);

  image23 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (buttonretourajout), image23);
  gtk_widget_set_size_request (image23, 100, 30);

  image13 = create_pixmap (window_ajout, "backgound.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed1), image13, 0, 0);
  gtk_widget_set_size_request (image13, 1024, 672);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_confirmer, "clicked",
                    G_CALLBACK (on_button_confirmer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourajout, "clicked",
                    G_CALLBACK (on_buttonretourajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajout, window_ajout, "window_ajout");
  GLADE_HOOKUP_OBJECT (window_ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window_ajout, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window_ajout, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (window_ajout, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (window_ajout, label, "label");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (window_ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (window_ajout, label8, "label8");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (window_ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (window_ajout, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (window_ajout, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (window_ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (window_ajout, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (window_ajout, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (window_ajout, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (window_ajout, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (window_ajout, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (window_ajout, button_confirmer, "button_confirmer");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_ajout, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_ajout, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (window_ajout, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_ajout, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (window_ajout, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window_ajout, eventbox67, "eventbox67");
  GLADE_HOOKUP_OBJECT (window_ajout, buttonretourajout, "buttonretourajout");
  GLADE_HOOKUP_OBJECT (window_ajout, image23, "image23");
  GLADE_HOOKUP_OBJECT (window_ajout, image13, "image13");

  return window_ajout;
}

GtkWidget*
create_window_modif (void)
{
  GtkWidget *window_modif;
  GtkWidget *fixed2;
  GtkWidget *entry_id2;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry10;
  GtkWidget *entryjour;
  GtkWidget *entrymois;
  GtkWidget *entryannee;
  GtkWidget *eventbox21;
  GtkWidget *label15;
  GtkWidget *eventbox22;
  GtkWidget *buttondevalidation;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label27;
  GtkWidget *eventbox23;
  GtkWidget *label_idex;
  GtkWidget *eventbox24;
  GtkWidget *label47;
  GtkWidget *eventbox25;
  GtkWidget *label18;
  GtkWidget *eventbox26;
  GtkWidget *label19;
  GtkWidget *eventbox27;
  GtkWidget *label20;
  GtkWidget *eventbox28;
  GtkWidget *label21;
  GtkWidget *eventbox29;
  GtkWidget *label22;
  GtkWidget *eventbox30;
  GtkWidget *label23;
  GtkWidget *eventbox31;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *eventbox32;
  GtkWidget *radiobutton4;
  GtkWidget *eventbox33;
  GtkWidget *label53;
  GtkWidget *entrychoix;
  GtkWidget *eventbox34;
  GtkWidget *buttondemodification;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;
  GtkWidget *eventbox35;
  GtkWidget *labelrepmodif;
  GtkWidget *eventbox68;
  GtkWidget *buttonretourmodif;
  GtkWidget *image24;
  GtkWidget *image14;

  window_modif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_modif), _("Modifier un menu"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_modif), fixed2);

  entry_id2 = gtk_entry_new ();
  gtk_widget_show (entry_id2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id2, 150, 80);
  gtk_widget_set_size_request (entry_id2, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id2), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 200, 260);
  gtk_widget_set_size_request (entry6, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 200, 300);
  gtk_widget_set_size_request (entry7, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed2), entry8, 200, 340);
  gtk_widget_set_size_request (entry8, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed2), entry10, 170, 200);
  gtk_widget_set_size_request (entry10, 180, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entryjour = gtk_entry_new ();
  gtk_widget_show (entryjour);
  gtk_fixed_put (GTK_FIXED (fixed2), entryjour, 150, 160);
  gtk_widget_set_size_request (entryjour, 50, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryjour), 8226);

  entrymois = gtk_entry_new ();
  gtk_widget_show (entrymois);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymois, 210, 160);
  gtk_widget_set_size_request (entrymois, 50, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymois), 8226);

  entryannee = gtk_entry_new ();
  gtk_widget_show (entryannee);
  gtk_fixed_put (GTK_FIXED (fixed2), entryannee, 270, 160);
  gtk_widget_set_size_request (entryannee, 80, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryannee), 8226);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox21, 0, 80);
  gtk_widget_set_size_request (eventbox21, 150, 30);

  label15 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label15);
  gtk_container_add (GTK_CONTAINER (eventbox21), label15);
  gtk_widget_set_size_request (label15, 150, 30);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox22, 310, 80);
  gtk_widget_set_size_request (eventbox22, 100, 30);

  buttondevalidation = gtk_button_new ();
  gtk_widget_show (buttondevalidation);
  gtk_container_add (GTK_CONTAINER (eventbox22), buttondevalidation);
  gtk_widget_set_size_request (buttondevalidation, 100, 30);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttondevalidation), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Valider  </span></b>"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox10), label27, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox23, 80, 120);
  gtk_widget_set_size_request (eventbox23, 264, 30);

  label_idex = gtk_label_new ("");
  gtk_widget_show (label_idex);
  gtk_container_add (GTK_CONTAINER (eventbox23), label_idex);
  gtk_widget_set_size_request (label_idex, 264, 30);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox24, 0, 160);
  gtk_widget_set_size_request (eventbox24, 150, 30);

  label47 = gtk_label_new (_("Date"));
  gtk_widget_show (label47);
  gtk_container_add (GTK_CONTAINER (eventbox24), label47);
  gtk_widget_set_size_request (label47, 150, 30);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox25, 0, 200);
  gtk_widget_set_size_request (eventbox25, 150, 30);

  label18 = gtk_label_new (_("Type"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox25), label18);
  gtk_widget_set_size_request (label18, 150, 30);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 0, 230);
  gtk_widget_set_size_request (eventbox26, 150, 30);

  label19 = gtk_label_new (_("Menu"));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox26), label19);
  gtk_widget_set_size_request (label19, 150, 30);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox27, 30, 260);
  gtk_widget_set_size_request (eventbox27, 150, 30);

  label20 = gtk_label_new (_("Entree"));
  gtk_widget_show (label20);
  gtk_container_add (GTK_CONTAINER (eventbox27), label20);
  gtk_widget_set_size_request (label20, 150, 30);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox28, 30, 300);
  gtk_widget_set_size_request (eventbox28, 150, 30);

  label21 = gtk_label_new (_("Plat Principal"));
  gtk_widget_show (label21);
  gtk_container_add (GTK_CONTAINER (eventbox28), label21);
  gtk_widget_set_size_request (label21, 150, 30);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox29, 32, 340);
  gtk_widget_set_size_request (eventbox29, 150, 30);

  label22 = gtk_label_new (_("Dessert"));
  gtk_widget_show (label22);
  gtk_container_add (GTK_CONTAINER (eventbox29), label22);
  gtk_widget_set_size_request (label22, 150, 30);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox30, 0, 380);
  gtk_widget_set_size_request (eventbox30, 150, 30);

  label23 = gtk_label_new (_("Regime"));
  gtk_widget_show (label23);
  gtk_container_add (GTK_CONTAINER (eventbox30), label23);
  gtk_widget_set_size_request (label23, 150, 30);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox31, 150, 380);
  gtk_widget_set_size_request (eventbox31, 110, 30);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Vegetarien"));
  gtk_widget_show (radiobutton3);
  gtk_container_add (GTK_CONTAINER (eventbox31), radiobutton3);
  gtk_widget_set_size_request (radiobutton3, 110, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox32, 270, 380);
  gtk_widget_set_size_request (eventbox32, 110, 30);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Standard"));
  gtk_widget_show (radiobutton4);
  gtk_container_add (GTK_CONTAINER (eventbox32), radiobutton4);
  gtk_widget_set_size_request (radiobutton4, 110, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox33, 0, 420);
  gtk_widget_set_size_request (eventbox33, 150, 30);

  label53 = gtk_label_new (_("Choix"));
  gtk_widget_show (label53);
  gtk_container_add (GTK_CONTAINER (eventbox33), label53);
  gtk_widget_set_size_request (label53, 150, 30);

  entrychoix = gtk_entry_new ();
  gtk_widget_show (entrychoix);
  gtk_fixed_put (GTK_FIXED (fixed2), entrychoix, 150, 420);
  gtk_widget_set_size_request (entrychoix, 250, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrychoix), 8226);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox34, 20, 460);
  gtk_widget_set_size_request (eventbox34, 150, 30);

  buttondemodification = gtk_button_new ();
  gtk_widget_show (buttondemodification);
  gtk_container_add (GTK_CONTAINER (eventbox34), buttondemodification);
  gtk_widget_set_size_request (buttondemodification, 150, 30);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttondemodification), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">       Modifier</span></b>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox35, 180, 460);
  gtk_widget_set_size_request (eventbox35, 205, 30);

  labelrepmodif = gtk_label_new ("");
  gtk_widget_show (labelrepmodif);
  gtk_container_add (GTK_CONTAINER (eventbox35), labelrepmodif);
  gtk_widget_set_size_request (labelrepmodif, 205, 30);

  eventbox68 = gtk_event_box_new ();
  gtk_widget_show (eventbox68);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox68, 16, 24);
  gtk_widget_set_size_request (eventbox68, 66, 29);

  buttonretourmodif = gtk_button_new ();
  gtk_widget_show (buttonretourmodif);
  gtk_container_add (GTK_CONTAINER (eventbox68), buttonretourmodif);
  gtk_widget_set_size_request (buttonretourmodif, 66, 29);

  image24 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (buttonretourmodif), image24);

  image14 = create_pixmap (window_modif, "backgound.png");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed2), image14, 0, 0);
  gtk_widget_set_size_request (image14, 1024, 680);

  g_signal_connect ((gpointer) buttondevalidation, "clicked",
                    G_CALLBACK (on_buttondevalidation_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttondemodification, "clicked",
                    G_CALLBACK (on_buttondemodification_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourmodif, "clicked",
                    G_CALLBACK (on_buttonretourmodif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_modif, window_modif, "window_modif");
  GLADE_HOOKUP_OBJECT (window_modif, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_modif, entry_id2, "entry_id2");
  GLADE_HOOKUP_OBJECT (window_modif, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window_modif, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window_modif, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window_modif, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window_modif, entryjour, "entryjour");
  GLADE_HOOKUP_OBJECT (window_modif, entrymois, "entrymois");
  GLADE_HOOKUP_OBJECT (window_modif, entryannee, "entryannee");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (window_modif, label15, "label15");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (window_modif, buttondevalidation, "buttondevalidation");
  GLADE_HOOKUP_OBJECT (window_modif, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_modif, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_modif, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_modif, label27, "label27");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (window_modif, label_idex, "label_idex");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (window_modif, label47, "label47");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (window_modif, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (window_modif, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (window_modif, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (window_modif, label21, "label21");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (window_modif, label22, "label22");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (window_modif, label23, "label23");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (window_modif, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (window_modif, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (window_modif, label53, "label53");
  GLADE_HOOKUP_OBJECT (window_modif, entrychoix, "entrychoix");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (window_modif, buttondemodification, "buttondemodification");
  GLADE_HOOKUP_OBJECT (window_modif, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_modif, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_modif, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_modif, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (window_modif, labelrepmodif, "labelrepmodif");
  GLADE_HOOKUP_OBJECT (window_modif, eventbox68, "eventbox68");
  GLADE_HOOKUP_OBJECT (window_modif, buttonretourmodif, "buttonretourmodif");
  GLADE_HOOKUP_OBJECT (window_modif, image24, "image24");
  GLADE_HOOKUP_OBJECT (window_modif, image14, "image14");

  return window_modif;
}

GtkWidget*
create_window_supp (void)
{
  GtkWidget *window_supp;
  GtkWidget *fixed3;
  GtkWidget *entry_idsup;
  GtkWidget *eventbox55;
  GtkWidget *label24;
  GtkWidget *eventbox56;
  GtkWidget *buttonde_supp;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label25;
  GtkWidget *eventbox57;
  GtkWidget *label29;
  GtkWidget *eventbox69;
  GtkWidget *buttonretoursupp;
  GtkWidget *image25;
  GtkWidget *image16;

  window_supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_supp), _("Supprimer un menu"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window_supp), fixed3);

  entry_idsup = gtk_entry_new ();
  gtk_widget_show (entry_idsup);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_idsup, 24, 108);
  gtk_widget_set_size_request (entry_idsup, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idsup), 8226);

  eventbox55 = gtk_event_box_new ();
  gtk_widget_show (eventbox55);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox55, 8, 68);
  gtk_widget_set_size_request (eventbox55, 368, 32);

  label24 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Entrer l'identifiant de menu a supprimer svp :)  </span></b>"));
  gtk_widget_show (label24);
  gtk_container_add (GTK_CONTAINER (eventbox55), label24);
  gtk_widget_set_size_request (label24, 368, 32);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox56, 24, 150);
  gtk_widget_set_size_request (eventbox56, 160, 30);

  buttonde_supp = gtk_button_new ();
  gtk_widget_show (buttonde_supp);
  gtk_container_add (GTK_CONTAINER (eventbox56), buttonde_supp);
  gtk_widget_set_size_request (buttonde_supp, 160, 30);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonde_supp), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("<b><span color=\"RED\"> Supprimer </span></b>"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox8), label25, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label25, 100, -1);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox57, 192, 120);
  gtk_widget_set_size_request (eventbox57, 232, 44);

  label29 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">           \n\n\n\n </span></b>"));
  gtk_widget_show (label29);
  gtk_container_add (GTK_CONTAINER (eventbox57), label29);
  gtk_widget_set_size_request (label29, 232, 44);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  eventbox69 = gtk_event_box_new ();
  gtk_widget_show (eventbox69);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox69, 40, 24);
  gtk_widget_set_size_request (eventbox69, 66, 29);

  buttonretoursupp = gtk_button_new ();
  gtk_widget_show (buttonretoursupp);
  gtk_container_add (GTK_CONTAINER (eventbox69), buttonretoursupp);
  gtk_widget_set_size_request (buttonretoursupp, 66, 29);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_container_add (GTK_CONTAINER (buttonretoursupp), image25);

  image16 = create_pixmap (window_supp, "backgound.png");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed3), image16, 0, 0);
  gtk_widget_set_size_request (image16, 1008, 680);

  g_signal_connect ((gpointer) buttonde_supp, "clicked",
                    G_CALLBACK (on_buttonde_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretoursupp, "clicked",
                    G_CALLBACK (on_buttonretoursupp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_supp, window_supp, "window_supp");
  GLADE_HOOKUP_OBJECT (window_supp, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_supp, entry_idsup, "entry_idsup");
  GLADE_HOOKUP_OBJECT (window_supp, eventbox55, "eventbox55");
  GLADE_HOOKUP_OBJECT (window_supp, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_supp, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (window_supp, buttonde_supp, "buttonde_supp");
  GLADE_HOOKUP_OBJECT (window_supp, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_supp, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_supp, image8, "image8");
  GLADE_HOOKUP_OBJECT (window_supp, label25, "label25");
  GLADE_HOOKUP_OBJECT (window_supp, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (window_supp, label29, "label29");
  GLADE_HOOKUP_OBJECT (window_supp, eventbox69, "eventbox69");
  GLADE_HOOKUP_OBJECT (window_supp, buttonretoursupp, "buttonretoursupp");
  GLADE_HOOKUP_OBJECT (window_supp, image25, "image25");
  GLADE_HOOKUP_OBJECT (window_supp, image16, "image16");

  return window_supp;
}

GtkWidget*
create_window_affiche (void)
{
  GtkWidget *window_affiche;
  GtkWidget *fixed5;
  GtkWidget *treeview;
  GtkWidget *eventbox58;
  GtkWidget *button_actualiser;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label26;
  GtkWidget *eventbox59;
  GtkWidget *button_rechercher2;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label28;
  GtkWidget *eventbox70;
  GtkWidget *buttonsuppdetree;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label58;
  GtkWidget *eventbox71;
  GtkWidget *buttonretouraffiche;
  GtkWidget *image26;
  GtkWidget *eventbox72;
  GtkWidget *labsup;
  GtkWidget *image17;

  window_affiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_affiche), _("Afficher le menu du semaine"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_affiche), fixed5);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview, 0, 110);
  gtk_widget_set_size_request (treeview, 912, 332);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox58, 8, 68);
  gtk_widget_set_size_request (eventbox58, 150, 30);

  button_actualiser = gtk_button_new ();
  gtk_widget_show (button_actualiser);
  gtk_container_add (GTK_CONTAINER (eventbox58), button_actualiser);
  gtk_widget_set_size_request (button_actualiser, 150, 30);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_actualiser), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">   actualiser</span></b>"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  eventbox59 = gtk_event_box_new ();
  gtk_widget_show (eventbox59);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox59, 208, 68);
  gtk_widget_set_size_request (eventbox59, 150, 30);

  button_rechercher2 = gtk_button_new ();
  gtk_widget_show (button_rechercher2);
  gtk_container_add (GTK_CONTAINER (eventbox59), button_rechercher2);
  gtk_widget_set_size_request (button_rechercher2, 150, 30);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_rechercher2), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Rechercher  </span></b>"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox11), label28, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  eventbox70 = gtk_event_box_new ();
  gtk_widget_show (eventbox70);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox70, 400, 68);
  gtk_widget_set_size_request (eventbox70, 150, 30);

  buttonsuppdetree = gtk_button_new ();
  gtk_widget_show (buttonsuppdetree);
  gtk_container_add (GTK_CONTAINER (eventbox70), buttonsuppdetree);
  gtk_widget_set_size_request (buttonsuppdetree, 150, 30);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonsuppdetree), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Supprimer  </span></b>"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox17), label58, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  eventbox71 = gtk_event_box_new ();
  gtk_widget_show (eventbox71);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox71, 16, 16);
  gtk_widget_set_size_request (eventbox71, 66, 29);

  buttonretouraffiche = gtk_button_new ();
  gtk_widget_show (buttonretouraffiche);
  gtk_container_add (GTK_CONTAINER (eventbox71), buttonretouraffiche);
  gtk_widget_set_size_request (buttonretouraffiche, 66, 29);

  image26 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_container_add (GTK_CONTAINER (buttonretouraffiche), image26);

  eventbox72 = gtk_event_box_new ();
  gtk_widget_show (eventbox72);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox72, 584, 68);
  gtk_widget_set_size_request (eventbox72, 180, 30);

  labsup = gtk_label_new ("");
  gtk_widget_show (labsup);
  gtk_container_add (GTK_CONTAINER (eventbox72), labsup);
  gtk_widget_set_size_request (labsup, 180, 30);

  image17 = create_pixmap (window_affiche, "backgound.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed5), image17, 0, 0);
  gtk_widget_set_size_request (image17, 1024, 680);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_actualiser, "clicked",
                    G_CALLBACK (on_button_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher2, "clicked",
                    G_CALLBACK (on_button_rechercher2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuppdetree, "clicked",
                    G_CALLBACK (on_buttonsuppdetree_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretouraffiche, "clicked",
                    G_CALLBACK (on_buttonretouraffiche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_affiche, window_affiche, "window_affiche");
  GLADE_HOOKUP_OBJECT (window_affiche, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_affiche, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (window_affiche, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (window_affiche, button_actualiser, "button_actualiser");
  GLADE_HOOKUP_OBJECT (window_affiche, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_affiche, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_affiche, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_affiche, label26, "label26");
  GLADE_HOOKUP_OBJECT (window_affiche, eventbox59, "eventbox59");
  GLADE_HOOKUP_OBJECT (window_affiche, button_rechercher2, "button_rechercher2");
  GLADE_HOOKUP_OBJECT (window_affiche, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window_affiche, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window_affiche, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_affiche, label28, "label28");
  GLADE_HOOKUP_OBJECT (window_affiche, eventbox70, "eventbox70");
  GLADE_HOOKUP_OBJECT (window_affiche, buttonsuppdetree, "buttonsuppdetree");
  GLADE_HOOKUP_OBJECT (window_affiche, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window_affiche, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window_affiche, image28, "image28");
  GLADE_HOOKUP_OBJECT (window_affiche, label58, "label58");
  GLADE_HOOKUP_OBJECT (window_affiche, eventbox71, "eventbox71");
  GLADE_HOOKUP_OBJECT (window_affiche, buttonretouraffiche, "buttonretouraffiche");
  GLADE_HOOKUP_OBJECT (window_affiche, image26, "image26");
  GLADE_HOOKUP_OBJECT (window_affiche, eventbox72, "eventbox72");
  GLADE_HOOKUP_OBJECT (window_affiche, labsup, "labsup");
  GLADE_HOOKUP_OBJECT (window_affiche, image17, "image17");

  return window_affiche;
}

GtkWidget*
create_window_recherche (void)
{
  GtkWidget *window_recherche;
  GtkWidget *fixed6;
  GtkWidget *entry9;
  GtkWidget *eventbox36;
  GtkWidget *label30;
  GtkWidget *eventbox37;
  GtkWidget *button1;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label31;
  GtkWidget *eventbox38;
  GtkWidget *labelrep;
  GtkWidget *eventbox39;
  GtkWidget *label32;
  GtkWidget *eventbox40;
  GtkWidget *labelmois;
  GtkWidget *eventbox41;
  GtkWidget *labeljour;
  GtkWidget *eventbox42;
  GtkWidget *labelannee;
  GtkWidget *eventbox43;
  GtkWidget *label36;
  GtkWidget *eventbox44;
  GtkWidget *labeltype;
  GtkWidget *eventbox45;
  GtkWidget *label38;
  GtkWidget *eventbox46;
  GtkWidget *labelentree;
  GtkWidget *eventbox47;
  GtkWidget *label40;
  GtkWidget *eventbox48;
  GtkWidget *labelplat;
  GtkWidget *eventbox49;
  GtkWidget *label42;
  GtkWidget *eventbox50;
  GtkWidget *labeldessert;
  GtkWidget *eventbox51;
  GtkWidget *label44;
  GtkWidget *eventbox52;
  GtkWidget *labelregime;
  GtkWidget *eventbox53;
  GtkWidget *label46;
  GtkWidget *eventbox54;
  GtkWidget *labelpour;
  GtkWidget *image15;
  GtkWidget *buttonretourrecherche;
  GtkWidget *image27;

  window_recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_recherche), _("Rechercher un menu"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window_recherche), fixed6);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed6), entry9, 120, 60);
  gtk_widget_set_size_request (entry9, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox36, 0, 60);
  gtk_widget_set_size_request (eventbox36, 120, 30);

  label30 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Id </span></b>"));
  gtk_widget_show (label30);
  gtk_container_add (GTK_CONTAINER (eventbox36), label30);
  gtk_widget_set_size_request (label30, 120, 30);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox37, 280, 60);
  gtk_widget_set_size_request (eventbox37, 90, 30);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (eventbox37), button1);
  gtk_widget_set_size_request (button1, 90, 30);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button1), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    OK </span></b>"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox12), label31, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label31, 47, 17);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox38, 380, 60);
  gtk_widget_set_size_request (eventbox38, 150, 30);

  labelrep = gtk_label_new ("");
  gtk_widget_show (labelrep);
  gtk_container_add (GTK_CONTAINER (eventbox38), labelrep);
  gtk_widget_set_size_request (labelrep, 150, 30);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox39, 8, 100);
  gtk_widget_set_size_request (eventbox39, 150, 30);

  label32 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Date </span></b>"));
  gtk_widget_show (label32);
  gtk_container_add (GTK_CONTAINER (eventbox39), label32);
  gtk_widget_set_size_request (label32, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox40, 200, 100);
  gtk_widget_set_size_request (eventbox40, 80, 30);

  labelmois = gtk_label_new ("");
  gtk_widget_show (labelmois);
  gtk_container_add (GTK_CONTAINER (eventbox40), labelmois);
  gtk_widget_set_size_request (labelmois, 80, 30);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox41, 120, 100);
  gtk_widget_set_size_request (eventbox41, 80, 30);

  labeljour = gtk_label_new ("");
  gtk_widget_show (labeljour);
  gtk_container_add (GTK_CONTAINER (eventbox41), labeljour);
  gtk_widget_set_size_request (labeljour, 80, 30);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox42, 280, 100);
  gtk_widget_set_size_request (eventbox42, 80, 30);

  labelannee = gtk_label_new ("");
  gtk_widget_show (labelannee);
  gtk_container_add (GTK_CONTAINER (eventbox42), labelannee);
  gtk_widget_set_size_request (labelannee, 80, 30);

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox43, 8, 140);
  gtk_widget_set_size_request (eventbox43, 150, 30);

  label36 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Type </span></b>"));
  gtk_widget_show (label36);
  gtk_container_add (GTK_CONTAINER (eventbox43), label36);
  gtk_widget_set_size_request (label36, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox44, 150, 140);
  gtk_widget_set_size_request (eventbox44, 150, 30);

  labeltype = gtk_label_new ("");
  gtk_widget_show (labeltype);
  gtk_container_add (GTK_CONTAINER (eventbox44), labeltype);
  gtk_widget_set_size_request (labeltype, 150, 30);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox45, 8, 190);
  gtk_widget_set_size_request (eventbox45, 150, 30);

  label38 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Entree </span></b>"));
  gtk_widget_show (label38);
  gtk_container_add (GTK_CONTAINER (eventbox45), label38);
  gtk_widget_set_size_request (label38, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox46, 150, 190);
  gtk_widget_set_size_request (eventbox46, 150, 30);

  labelentree = gtk_label_new ("");
  gtk_widget_show (labelentree);
  gtk_container_add (GTK_CONTAINER (eventbox46), labelentree);
  gtk_widget_set_size_request (labelentree, 150, 30);

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox47, 8, 250);
  gtk_widget_set_size_request (eventbox47, 150, 30);

  label40 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Plat principal </span></b>"));
  gtk_widget_show (label40);
  gtk_container_add (GTK_CONTAINER (eventbox47), label40);
  gtk_widget_set_size_request (label40, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  eventbox48 = gtk_event_box_new ();
  gtk_widget_show (eventbox48);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox48, 150, 250);
  gtk_widget_set_size_request (eventbox48, 150, 30);

  labelplat = gtk_label_new ("");
  gtk_widget_show (labelplat);
  gtk_container_add (GTK_CONTAINER (eventbox48), labelplat);
  gtk_widget_set_size_request (labelplat, 150, 30);

  eventbox49 = gtk_event_box_new ();
  gtk_widget_show (eventbox49);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox49, 8, 300);
  gtk_widget_set_size_request (eventbox49, 150, 30);

  label42 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">    Dessert </span></b>"));
  gtk_widget_show (label42);
  gtk_container_add (GTK_CONTAINER (eventbox49), label42);
  gtk_widget_set_size_request (label42, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox50, 150, 300);
  gtk_widget_set_size_request (eventbox50, 150, 30);

  labeldessert = gtk_label_new ("");
  gtk_widget_show (labeldessert);
  gtk_container_add (GTK_CONTAINER (eventbox50), labeldessert);
  gtk_widget_set_size_request (labeldessert, 150, 30);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox51, 8, 350);
  gtk_widget_set_size_request (eventbox51, 150, 30);

  label44 = gtk_label_new (_("<b><span color=\"black\">    Regime </span></b>"));
  gtk_widget_show (label44);
  gtk_container_add (GTK_CONTAINER (eventbox51), label44);
  gtk_widget_set_size_request (label44, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox52, 150, 350);
  gtk_widget_set_size_request (eventbox52, 150, 30);

  labelregime = gtk_label_new ("");
  gtk_widget_show (labelregime);
  gtk_container_add (GTK_CONTAINER (eventbox52), labelregime);
  gtk_widget_set_size_request (labelregime, 150, 30);

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox53, 8, 400);
  gtk_widget_set_size_request (eventbox53, 150, 30);

  label46 = gtk_label_new (_("<b><span color=\"black\">    Ce repas est pour: </span></b>"));
  gtk_widget_show (label46);
  gtk_container_add (GTK_CONTAINER (eventbox53), label46);
  gtk_widget_set_size_request (label46, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox54, 160, 400);
  gtk_widget_set_size_request (eventbox54, 230, 30);

  labelpour = gtk_label_new ("");
  gtk_widget_show (labelpour);
  gtk_container_add (GTK_CONTAINER (eventbox54), labelpour);
  gtk_widget_set_size_request (labelpour, 230, 30);

  image15 = create_pixmap (window_recherche, "backgound.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed6), image15, 0, 0);
  gtk_widget_set_size_request (image15, 1024, 664);

  buttonretourrecherche = gtk_button_new ();
  gtk_widget_show (buttonretourrecherche);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonretourrecherche, 32, 16);
  gtk_widget_set_size_request (buttonretourrecherche, 66, 29);

  image27 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (buttonretourrecherche), image27);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourrecherche, "clicked",
                    G_CALLBACK (on_buttonretourrecherche_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label30), entry9);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_recherche, window_recherche, "window_recherche");
  GLADE_HOOKUP_OBJECT (window_recherche, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_recherche, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (window_recherche, label30, "label30");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (window_recherche, button1, "button1");
  GLADE_HOOKUP_OBJECT (window_recherche, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window_recherche, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window_recherche, image12, "image12");
  GLADE_HOOKUP_OBJECT (window_recherche, label31, "label31");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (window_recherche, labelrep, "labelrep");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (window_recherche, label32, "label32");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (window_recherche, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (window_recherche, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (window_recherche, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (window_recherche, label36, "label36");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (window_recherche, labeltype, "labeltype");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (window_recherche, label38, "label38");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (window_recherche, labelentree, "labelentree");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (window_recherche, label40, "label40");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox48, "eventbox48");
  GLADE_HOOKUP_OBJECT (window_recherche, labelplat, "labelplat");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox49, "eventbox49");
  GLADE_HOOKUP_OBJECT (window_recherche, label42, "label42");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (window_recherche, labeldessert, "labeldessert");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (window_recherche, label44, "label44");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (window_recherche, labelregime, "labelregime");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (window_recherche, label46, "label46");
  GLADE_HOOKUP_OBJECT (window_recherche, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (window_recherche, labelpour, "labelpour");
  GLADE_HOOKUP_OBJECT (window_recherche, image15, "image15");
  GLADE_HOOKUP_OBJECT (window_recherche, buttonretourrecherche, "buttonretourrecherche");
  GLADE_HOOKUP_OBJECT (window_recherche, image27, "image27");

  return window_recherche;
}

GtkWidget*
create_first_window (void)
{
  GtkWidget *first_window;
  GtkWidget *fixed7;
  GtkWidget *eventbox63;
  GtkWidget *button_ajouter;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image19;
  GtkWidget *label55;
  GtkWidget *eventbox64;
  GtkWidget *button_supprimer;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image21;
  GtkWidget *label57;
  GtkWidget *eventbox65;
  GtkWidget *button_modifier;
  GtkWidget *alignment16;
  GtkWidget *hbox15;
  GtkWidget *image20;
  GtkWidget *label56;
  GtkWidget *eventbox66;
  GtkWidget *button_afficher;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image18;
  GtkWidget *label54;
  GtkWidget *image22;

  first_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (first_window), _("Gestion de Menu"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (first_window), fixed7);

  eventbox63 = gtk_event_box_new ();
  gtk_widget_show (eventbox63);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox63, 40, 376);
  gtk_widget_set_size_request (eventbox63, 200, 80);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_container_add (GTK_CONTAINER (eventbox63), button_ajouter);
  gtk_widget_set_size_request (button_ajouter, 200, 80);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image19 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox14), image19, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\">      Ajouter</span></b>"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox14), label55, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label55, 110, 20);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  eventbox64 = gtk_event_box_new ();
  gtk_widget_show (eventbox64);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox64, 272, 376);
  gtk_widget_set_size_request (eventbox64, 200, 80);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_container_add (GTK_CONTAINER (eventbox64), button_supprimer);
  gtk_widget_set_size_request (button_supprimer, 200, 80);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image21 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox16), image21, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\">       Supprimer</span></b>"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox16), label57, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label57, 110, 20);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  eventbox65 = gtk_event_box_new ();
  gtk_widget_show (eventbox65);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox65, 504, 376);
  gtk_widget_set_size_request (eventbox65, 200, 80);

  button_modifier = gtk_button_new ();
  gtk_widget_show (button_modifier);
  gtk_container_add (GTK_CONTAINER (eventbox65), button_modifier);
  gtk_widget_set_size_request (button_modifier, 200, 80);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_modifier), alignment16);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox15);

  image20 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox15), image20, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_(" <b><span color=\"blue\">       Modifier</span></b>"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox15), label56, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label56, 110, 20);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  eventbox66 = gtk_event_box_new ();
  gtk_widget_show (eventbox66);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox66, 736, 376);
  gtk_widget_set_size_request (eventbox66, 200, 80);

  button_afficher = gtk_button_new ();
  gtk_widget_show (button_afficher);
  gtk_container_add (GTK_CONTAINER (eventbox66), button_afficher);
  gtk_widget_set_size_request (button_afficher, 200, 80);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_afficher), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image18 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox13), image18, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\">    Afficher</span></b>"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox13), label54, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  image22 = create_pixmap (first_window, "backgound.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed7), image22, 0, 0);
  gtk_widget_set_size_request (image22, 1024, 680);

  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher, "clicked",
                    G_CALLBACK (on_button_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (first_window, first_window, "first_window");
  GLADE_HOOKUP_OBJECT (first_window, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (first_window, eventbox63, "eventbox63");
  GLADE_HOOKUP_OBJECT (first_window, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (first_window, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (first_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (first_window, image19, "image19");
  GLADE_HOOKUP_OBJECT (first_window, label55, "label55");
  GLADE_HOOKUP_OBJECT (first_window, eventbox64, "eventbox64");
  GLADE_HOOKUP_OBJECT (first_window, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (first_window, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (first_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (first_window, image21, "image21");
  GLADE_HOOKUP_OBJECT (first_window, label57, "label57");
  GLADE_HOOKUP_OBJECT (first_window, eventbox65, "eventbox65");
  GLADE_HOOKUP_OBJECT (first_window, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (first_window, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (first_window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (first_window, image20, "image20");
  GLADE_HOOKUP_OBJECT (first_window, label56, "label56");
  GLADE_HOOKUP_OBJECT (first_window, eventbox66, "eventbox66");
  GLADE_HOOKUP_OBJECT (first_window, button_afficher, "button_afficher");
  GLADE_HOOKUP_OBJECT (first_window, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (first_window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (first_window, image18, "image18");
  GLADE_HOOKUP_OBJECT (first_window, label54, "label54");
  GLADE_HOOKUP_OBJECT (first_window, image22, "image22");

  return first_window;
}

