/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_ajout (void);
GtkWidget* create_window_modif (void);
GtkWidget* create_window_supp (void);
GtkWidget* create_window_affiche (void);
GtkWidget* create_window_recherche (void);
GtkWidget* create_first_window (void);
