/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAdmin (void);
GtkWidget* create_windowAfficher (void);
GtkWidget* create_windowAjouter (void);
GtkWidget* create_windowAuth (void);
GtkWidget* create_windowModifier (void);
GtkWidget* create_windowModifier2 (void);
GtkWidget* create_windowChercher (void);
GtkWidget* create_windowAffichert (void);
GtkWidget* create_windowSupprimer (void);
GtkWidget* create_Espace_technicien (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_rechercher_capteur (void);
GtkWidget* create_dashboard (void);
