/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowAdmin;
  GtkWidget *windowAfficher;
  GtkWidget *windowAjouter;
  GtkWidget *windowAuth;
  GtkWidget *windowModifier;
  GtkWidget *windowModifier2;
  GtkWidget *windowChercher;
  GtkWidget *windowAffichert;
  GtkWidget *windowSupprimer;
  GtkWidget *Espace_technicien;
  GtkWidget *modifier_capteur;
  GtkWidget *ajouter_capteur;
  GtkWidget *supprimer_capteur;
  GtkWidget *rechercher_capteur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*windowAdmin = create_windowAdmin ();
  gtk_widget_show (windowAdmin);
  windowAfficher = create_windowAfficher ();
  gtk_widget_show (windowAfficher);
  windowAjouter = create_windowAjouter ();
  gtk_widget_show (windowAjouter);*/
  windowAuth = create_windowAuth ();
  gtk_widget_show (windowAuth);
  /*windowModifier = create_windowModifier ();
  gtk_widget_show (windowModifier);
  windowModifier2 = create_windowModifier2 ();
  gtk_widget_show (windowModifier2);
  windowChercher = create_windowChercher ();
  gtk_widget_show (windowChercher);
  windowAffichert = create_windowAffichert ();
  gtk_widget_show (windowAffichert);
  windowSupprimer = create_windowSupprimer ();
  gtk_widget_show (windowSupprimer);
  Espace_technicien = create_Espace_technicien ();
  gtk_widget_show (Espace_technicien);
  modifier_capteur = create_modifier_capteur ();
  gtk_widget_show (modifier_capteur);
  ajouter_capteur = create_ajouter_capteur ();
  gtk_widget_show (ajouter_capteur);
  supprimer_capteur = create_supprimer_capteur ();
  gtk_widget_show (supprimer_capteur);
  rechercher_capteur = create_rechercher_capteur ();
  gtk_widget_show (rechercher_capteur);*/

  gtk_main ();
  return 0;
}

